Models/Candidate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace HRMS.Models
{
    public class Candidate
    {
        public int CandidateID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; } 
        public string ShortDesc { get; set; }
        public string Status { get; set; }
        public string CVFilename { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; } 
        
    } 
}

Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using HRMS.Models;
using System.Data.Entity;
using System.ComponentModel;
using System.IO;
using System.Data;

namespace HRMS.Controllers
{
    public class CandidateController : Controller
    {
        //
        // GET: /Candidate/
        HRMSContext _db = new HRMSContext();

        public ActionResult Index()
        {
            try
            {
                 var candidates = _db.Candidates;
                 return View(candidates);
            }
            catch (Exception ex)
            {
                TempData["color"] = "red";
                TempData["result"] = ex.Message;

            }
            return View();

        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Candidate candidate)
        {
            try
            {
                using (var context = new HRMSContext()) 
                {

                    candidate.CreatedDate = DateTime.Now;
                    context.Candidates.Add(candidate);
                    context.SaveChanges();  


                    //upload candidate's resume
                    //drops database and data with it
                    //Database.SetInitializer<CandidateContext>(new DropCreateDatabaseAlways<CandidateContext>()); 
                    if (Request.Files["cvfile"].ContentLength > 0)
                    {
                        //get last insert id for saving the resume
                        string filename = candidate.Firstname + "_" + candidate.Lastname + "_" + candidate.CandidateID;

                        string extension = System.IO.Path.GetExtension(Request.Files["cvfile"].FileName);

                        string path = string.Format("{0}/{1}{2}", Server.MapPath("~/Documents/cv"),
                            filename, extension);

                        if (System.IO.File.Exists(path))
                        {
                            System.IO.File.Delete(path);

                        }

                        Request.Files["cvfile"].SaveAs(path);

                        Candidate c = _db.Candidates.SingleOrDefault(i => i.CandidateID == candidate.CandidateID);
                        c.CVFilename = filename;
                        _db.SaveChanges();
                    }
                    else
                    {
                        candidate.CVFilename = "";
                    }

                }
                TempData["color"] = "green";
                TempData["result"] = "Successfully Saved New Candidate To Database.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Alert = ex.Message;
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                Candidate c = _db.Candidates.First(i => i.CandidateID == id);
                _db.Candidates.Remove(c);
                _db.SaveChanges();

                TempData["color"] = "green";
                TempData["result"] = "Successfully Deleted Candidate Record From Database.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {//TODO: Log error				
                TempData["color"] = "red";
                TempData["result"] = ex.Message;
                return RedirectToAction("Index");
            } 
        }

        public ActionResult Update(int id)
        {
            return View(_db.Candidates.Where(i => i.CandidateID == id).FirstOrDefault());
        }

        [HttpPost]
        public ActionResult Update(Candidate candidate, int id)
        {

            using (var _db = new HRMSContext())
            {
                Candidate c = _db.Candidates.SingleOrDefault(i => i.CandidateID == id);

                c.Firstname = candidate.Firstname;
                c.Lastname = candidate.Lastname;
                c.Title = candidate.Title;
                c.Email = candidate.Email;
                c.Telephone = candidate.Telephone;
                c.Status = candidate.Status;
                c.ShortDesc = candidate.ShortDesc;

                if (Request.Files["cvfile"].ContentLength > 0)
                {
                    //get last insert id for saving the resume
                    string filename = candidate.Firstname + "_" + candidate.Lastname + "_" + id;

                    string extension = System.IO.Path.GetExtension(Request.Files["cvfile"].FileName);

                    string path = string.Format("{0}/{1}{2}", Server.MapPath("~/Documents/cv"),
                        filename, extension);

                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                    Request.Files["cvfile"].SaveAs(path);

                    candidate.CVFilename = filename + "." + extension;
                }
                else
                {
                    candidate.CVFilename = "";
                }

                c.CVFilename = candidate.CVFilename;
                _db.SaveChanges();

                TempData["color"] = "green";
                TempData["result"] = "Successfully Updated Candidate Record.";
            }

            return RedirectToAction("Index");
        }
        public ViewResult View(int id)
        {
            TempData["isupdate"] = "no";
            return View(_db.Candidates.Where(i => i.CandidateID == id).FirstOrDefault());
        }

        
    }
}

Views/Candidate/Create.cshtml
@model HRMS.Models.Candidate
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "validate_form", enctype = "multipart/form-data" }))
{

    <div class="box grid_16">
        <h2 class="box_head">Form Elements</h2>
        <div class="controls">
            <a href="#" class="grabber"></a>
            <a href="#" class="toggle"></a>
        </div>
        <div class="toggle_container">
            <div class="block">
                 <h2 class="section">Candidate Information</h2>
                <div class="columns">
                    <div class="col_100">
                        <div class="col_40 no_border_left">
                            <fieldset>
                                <label>Given Name</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Firstname, new { @id = "required_fname", @class = "required" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_40">
                            <fieldset>
                                <label>Surname</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Lastname, new { @id = "required_lname", @class = "required" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_20">
                            <fieldset>
                                <label>Title</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Title)
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="bottom">
                                <label>Email Address</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Email, new { @id = "required_email", @class = "required email" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="bottom">
                                <label>Telephone</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Telephone, new { type = "number", @id = "required_1d", @class = "required" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="right bottom">
                                <label for="file_upload">Upload CV</label>
                                <div class="clearfix">
                                    <input type="file" name="cvfile" id="fileupload" class="uniform">
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="bottom">
                                <label>Status</label>
                                <div class="clearfix">
                                    @Html.DropDownListFor(m => m.Status, new SelectList(
                              new List<Object>{ 
                                   new { id = 0 , status = "Please select One"  }, 
                                   new { id = 1 , status = "In File" },
                                   new { id = 2 , status = "For Interview" },
                                   new { id = 3 , status = "Offer Sent"}
                                },
                              "id",
                              "status",
                              0), new { @class = "uniform full_width" })
                                </div>
                            </fieldset>
                        </div>
                    </div>

                    <div class="col_100">
                        <fieldset class="label_top top">
                            <label for="text_field_inline">A Short Description</label>
                            <div>
                                @Html.TextAreaFor(m => m.ShortDesc)
                            </div>
                        </fieldset>
                    </div>
                </div>


                <div class="button_bar clearfix">
                    <button class="light send_right" type="reset">
                        <span>Reset</span>
                    </button>
                    <button class="dark" type="submit">
                        <img src="images/icons/small/white/mail.png">
                        <span>Save Profile</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
}

Views/Candidate/Index.cshtml
@model IEnumerable<HRMS.Models.Candidate>
@{
    ViewBag.Title = "Index";
}

@if(TempData["color"] != null)
{
<div class="box grid_16">
    <div class="toggle_container">
        <div class="block">
            <div class="section"> 
                <div class="alert dismissible alert_@TempData["color"]">
                    <img height="24" width="24" src="~/Content/Images/icons/small/white/facebook_like.png">
                   @TempData["result"]
                </div>  
            </div>
        </div>
    </div>
</div>
}



<div class="box grid_16 tabs">
    <ul id="touch_sort" class="tab_header clearfix">
        <li><a href="#tabs-1">Available</a></li>
        <li><a href="#tabs-2">Hiring Process<span>(no pagination)</span></a></li>
        <li><a href="#tabs-3">Blocked Candidate</a></li>
    </ul>
    <div class="controls">
        <a href="#" class="grabber"></a>
        <a href="#" class="toggle"></a>
    </div>
    <div class="toggle_container">
        <div id="tabs-1" class="block">
            <div id="dt2">
                <table class=" datatable">
                    <thead>
                        <tr>
                            <th>Candidate Name</th>
                            <th>Email Address</th>
                            <th>Contact</th>
                            <th>Status</th>
                            <th style="width:10%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var candidate in Model)
                        {
                        <tr class="gradeX">
                            <td>@candidate.Title @candidate.Firstname @candidate.Lastname</td>
                            <td>@candidate.Email</td>
                            <td>@candidate.Telephone</td>
                            <td class="center">@candidate.Status</td>
                            <td class="center">  
                                <span class="button tiny light">
                               @Html.ActionLink("View", "View", new { id = candidate.CandidateID  }, new { @class = "ui-icon ui-icon-zoomout" })  
                                </span>
                                <span class="button tiny light">
                               @Html.ActionLink("Delete", "Delete", new { id = candidate.CandidateID  }, new { @class = "deleteLink ui-icon ui-icon-trash" })  
                                </span>
                                <span class="button tiny light">
                               @Html.ActionLink("Update", "Update", new { id = candidate.CandidateID  }, new { @class = "ui-icon ui-icon-pencil" })  
                                </span>
                            </td>
                        </tr> 
                        }
                    </tbody>
                </table>
                
            </div>
        </div>
        <div id="tabs-2" class="block">
            <div class="section">
                <p>Information about the Table can go here, or another table could go here or pretty much anything could go here!</p>
            </div>
        </div>
        <div id="tabs-3" class="block">
            <div class="section">
                <p>Information about the Table can go here, or another table could go here or pretty much anything could go here!</p>
            </div>
        </div>
    </div>
</div>

 

<div class="display_none">
                <div id="confirm-delete" class="dialog_content narrow no_dialog_titlebar" title="Delete Confirmation">
                    <div class="block">
                        <div class="section">
                            <h1>Delete File</h1>
                            <div class="dashed_line"></div>
                            <p>Please confirm that you want to delete this record.</p>
                        </div>
                        @*<div class="button_bar clearfix">
                            <button class="delete_confirm dark red no_margin_bottom close_dialog">
                                <div class="ui-icon ui-icon-check"></div>
                                <span>Sure</span>
                            </button>
                            <button class="light send_right close_dialog">
                                <div class="ui-icon ui-icon-closethick"></div>
                                <span>Cancel</span>
                            </button>
                        </div>*@
                    </div>
                </div>
            </div>

<script>
    $(document).ready(function () {
        $("#confirm-delete").dialog({
            autoOpen: false,
            modal: true,
            resizable: false,
            height: 180,
        });

        $(".deleteLink").click(function (e) {
            e.preventDefault();
            var targetUrl = $(this).attr("href");

            $("#confirm-delete").dialog({
                buttons: {
                    "Confirm": function () {
                        window.location.href = targetUrl;
                    },
                    "Cancel": function () {
                        $(this).dialog("close");
                    }
                }
            });

            $("#confirm-delete").dialog("open");
        });

    });

</script>

Views/Candidate/Update.cshtml
@model HRMS.Models.Candidate
@{
    ViewBag.Title = "Update";
}

@using (Html.BeginForm("Update", "Candidate", FormMethod.Post, new { @class = "validate_form", enctype = "multipart/form-data" }))
{
    if (ViewBag.Alert != null)
    { 
    <div class="box grid_16">
        <div class="toggle_container">
            <div class="block">
                <div class="section">
                    <div class="alert alert_red">
                        <img height="24" width="24" src="images/icons/small/white/alarm_bell.png">
                        @ViewBag.Alert
                    </div>
                </div>
            </div>
        </div>
    </div>
    }
   
    <div class="box grid_16">
        <h2 class="box_head">Form Elements</h2>
        <div class="controls">
            <a href="#" class="grabber"></a>
            <a href="#" class="toggle"></a>
        </div>
        <div class="toggle_container">
            <div class="block">
                 <h2 class="section">Candidate Information</h2>
                <div class="columns">
                    <div class="col_100">
                        <div class="col_40 no_border_left">
                            <fieldset>
                                <label>Given Name</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Firstname, new { @id = "required_fname", @class = "required" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_40">
                            <fieldset>
                                <label>Surname</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Lastname, new { @id = "required_lname", @class = "required" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_20">
                            <fieldset>
                                <label>Title</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Title)
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="bottom">
                                <label>Email Address</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Email, new { @id = "required_email", @class = "required email" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="bottom">
                                <label>Telephone</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Telephone, new { type = "number", @id = "required_1d", @class = "required" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="right bottom">
                                <label for="file_upload">Upload CV</label>
                                <div class="clearfix">
                                    <input type="file" name="cvfile" id="fileupload" class="uniform">
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="bottom">
                                <label>Status</label>
                                <div class="clearfix">
                                    @Html.DropDownListFor(m => m.Status, new SelectList(
                              new List<Object>{ 
                                   new { id = 0 , status = "Please select One"  }, 
                                   new { id = 1 , status = "In File" },
                                   new { id = 2 , status = "For Interview" },
                                   new { id = 3 , status = "Offer Sent"}
                                },
                              "id",
                              "status",
                              0), new { @class = "uniform full_width" })
                                </div>
                            </fieldset>
                        </div>
                    </div>

                    <div class="col_100">
                        <fieldset class="label_top top">
                            <label for="text_field_inline">A Short Description</label>
                            <div>
                                @Html.TextAreaFor(m => m.ShortDesc)
                            </div>
                        </fieldset>
                    </div>
                </div>


                <div class="button_bar clearfix">
                    <button class="light send_right" type="reset">
                        <span>Reset</span>
                    </button>
                    <button class="dark" type="submit">
                        <img src="images/icons/small/white/mail.png">
                        <span>Save Profile</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
}

Views/Candidate/View.cshtml
@model HRMS.Models.Candidate
@{
    ViewBag.Title = "View";
}


@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "validate_form", enctype = "multipart/form-data" }))
{
    

    <div class="box grid_16">
        <h2 class="box_head">Form Elements</h2>
        <div class="controls">
            <a href="#" class="grabber"></a>
            <a href="#" class="toggle"></a>
        </div>
        <div class="toggle_container">
            <div class="block">
                <h2 class="section">Candidate Information</h2>
                <div class="columns">
                    <div class="col_100">
                        <div class="col_40 no_border_left">
                            <fieldset>
                                <label>Given Name</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Firstname, new { @readonly="readonly" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_40">
                            <fieldset>
                                <label>Surname</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Lastname, new { @readonly="readonly" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_20">
                            <fieldset>
                                <label>Title</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Title, new { @readonly="readonly" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="bottom">
                                <label>Email Address</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Email, new { @readonly="readonly" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="bottom">
                                <label>Telephone</label>
                                <div class="clearfix">
                                    @Html.TextBoxFor(m => m.Telephone, new { @readonly="readonly" })
                                </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="right bottom">
                                <label for="file_upload">Candidate CV</label>
                                <div class="clearfix">
                                   <a href="~/Documents/cv/Petar_Prokop_1006YY.pdf" target="_blank" id="downloadfile" class="button light">
                                        <img src="~/Content/Images/icons/small/grey/download.png">
												<span>View Document</span></a> 
                                 </div>
                            </fieldset>
                        </div>
                        <div class="col_25">
                            <fieldset class="bottom">
                                <label>Status</label>
                                <div class="clearfix"> 
                                    @Html.TextBoxFor(m => m.Status, new { @readonly="readonly" })
                                </div>
                            </fieldset>
                        </div>
                    </div>

                    <div class="col_100">
                        <fieldset class="label_top top">
                            <label for="text_field_inline">A Short Description</label>
                            <div>
                                @Html.TextAreaFor(m => m.ShortDesc)
                            </div>
                        </fieldset>
                    </div>
                </div>

            </div>
        </div>
    </div>
}  