Models/Recruit.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace HRMS.Models
{
    public class Opening
    {
        public int OpeningID { get; set; }
        public string JobTitle { get; set; }
        public string JobDesc { get; set; }
        public string Location { get; set; }
        public string EmplType { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int StageID { get; set; }
    }

    public class Stage
    {
        public int StageID { get; set; }
        public string Desc { get; set; }
        public int Seq { get; set; }
    }

}

Controllers/RecruitController.cs
using HRMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace HRMS.Controllers
{
    public class RecruitController : Controller
    {
        //
        // GET: /Recruit/
        HRMSContext _db = new HRMSContext(); 


        public ActionResult Index()
        {
            return View();
        }
         

        public ActionResult Create()
        {
            return View();
             
        }

        [HttpPost]
        public ActionResult Create(Opening opening)
        {
            try
            {
                using (var context = new HRMSContext())
                { 
                    opening.CreatedDate = DateTime.Now; 
                    context.Openings.Add(opening);
                    context.SaveChanges(); 
                }
            }
            catch (Exception ex)
            {
                TempData["color"] = "red";
                TempData["result"] = ex.Message;
            }

            return new RedirectResult(Url.Action("Hire", new { id = opening.OpeningID }) + "?#tabs-2");
             
        }
        [HttpGet]
        public ActionResult Hire(int id)
        {
            return View(_db.Openings.Where(i => i.OpeningID == id).FirstOrDefault());
        } 

        public ActionResult Stage()
        {
            var stages = (from c in _db.Stages   
                             orderby c.Seq ascending
                             select c);
            return View(stages);
        }

        public ActionResult StageForm()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StageForm(Stage stage)
        {
            try
            {
                using (var context = new HRMSContext())
                {
                    context.Stages.Add(stage);
                    context.SaveChanges();

                    //get last sequence
                    var idKey = (from c in context.Stages // the table1 here has red line under it.
                                 orderby c.Seq descending
                                 select c).First();

                    int last = idKey.Seq;

                    Stage s = _db.Stages.SingleOrDefault(i => i.StageID == stage.StageID);
                    s.Seq = last + 1;
                    _db.SaveChanges();

                }

                TempData["color"] = "green";
                TempData["result"] = "Successfully Saved New Stage Record Database.";
            }
            catch (Exception ex)
            {
                TempData["color"] = "red";
                TempData["result"] = ex.Message;
            }

            return RedirectToAction("Stage");
        }

        [HttpPost]
        public ActionResult UpdateStage(Stage stage, int id)
        {
            using (var _db = new HRMSContext())
            {
                Stage s = _db.Stages.SingleOrDefault(i => i.StageID == id);

                //get last sequence
                var idKey = (from c in _db.Stages // the table1 here has red line under it.
                             orderby c.Seq descending
                             select c).First();

                int last = idKey.Seq;

                s.Desc = stage.Desc;
                _db.SaveChanges();
                TempData["color"] = "green";
                TempData["result"] = "Successfully Updated Candidate Record.";
            }

            return RedirectToAction("Stage");
        }

        public ActionResult UpdateStage(int id)
        {
            return View(_db.Stages.Where(i => i.StageID == id).FirstOrDefault());
        }

        public ActionResult DeleteStage(int id)
        {
            try
            {
                Stage s = _db.Stages.First(i => i.StageID == id);
                _db.Stages.Remove(s);
                _db.SaveChanges();

                TempData["color"] = "green";
                TempData["result"] = "Successfully Deleted Stage From Database.";
                return RedirectToAction("Stage");
            }
            catch (Exception ex)
            {//TODO: Log error				
                TempData["color"] = "red";
                TempData["result"] = ex.Message;
                return RedirectToAction("Stage");
            }
        }
        
       [HttpGet]
        public ActionResult UpdateStageSeq(Stage stage, string seq)
        {

            using (var _db = new HRMSContext())
            {
                //update all sequence value to 0

                string[] sq = seq.Split(',');
                foreach (var item in sq)
                {
                    int q = Convert.ToInt32(item);
                    Stage s = _db.Stages.SingleOrDefault(i => i.StageID == q);
                    s.Seq = 0;
                    _db.SaveChanges();
                }

                foreach (var item in sq)
                {
                    int q = Convert.ToInt32(item);
                    Stage s = _db.Stages.SingleOrDefault(i => i.StageID == q);

                    //get last sequence
                    var idKey = (from c in _db.Stages // the table1 here has red line under it.
                                 orderby c.Seq descending
                                 select c).First();

                    int last = idKey.Seq;
                    s.Seq = last + 1;
                    _db.SaveChanges();
                }
            }
            //update seq field to 1,2,3... so on and so forth
            return RedirectToAction("Stage");
        }
    }
}

Views/Recruit/Create.cshtml
@model HRMS.Models.Opening
@{
    ViewBag.Title = "Create";
}
 

<div class="box grid_16 tabs">
     <h2 class="box_head">Form Elements</h2>
        <div class="controls">
            <a href="#" class="grabber"></a>
            <a href="#" class="toggle"></a>
        </div>
    <div class="controls">
        <a href="#" class="grabber"></a>
        <a href="#" class="toggle"></a>
        <a href="#" class="show_all_tabs"></a>
    </div>
    <div class="toggle_container">

            <h2 class="section">Job Opening</h2>
            @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "validate_form" }))
            {
            <fieldset class="label_side label_small top">
                <label for="text_field_inline">Position</label>
                <div>
                     @Html.TextBoxFor(m => m.JobTitle, new { @id = "required_fname", @class = "required" })
                </div>
            </fieldset>

            <fieldset class="label_top">
                <label for="text_field_inline">Job Description</label>
                <div>
                    @Html.TextAreaFor(m => m.JobDesc, new { @id = "tiny_input", @class = " required" })
                </div>
            </fieldset>
            <div class="columns clearfix">
                <div class="col_50">
                    <fieldset class="label_side label_small top bottom">
                        <label for="text_field_inline">Location</label>
                        <div>
                             @Html.TextBoxFor(m => m.Location, new { @id = "required_fname", @class = "required" })
                            <div class="required_tag"></div>
                        </div>
                    </fieldset>
                </div>
                <div class="col_50">
                    <fieldset class="label_side label_small top right bottom">
                        <label for="text_field_inline">Emp Type</label>
                        <div>
                             @Html.TextBoxFor(m => m.EmplType, new { @id = "required_fname", @class = "required" })
                            <div class="required_tag"></div>
                        </div>
                    </fieldset>
                </div>
            </div>
                <div class="button_bar clearfix">
                    <button class="dark" type="submit">
                        <img src="images/icons/small/white/mail.png">
                        <span>Send</span>
                    </button>
                    <button class="light send_right" type="reset">
                        <span>Reset</span>
                    </button>
                </div>
            }
         
    </div>
</div>
 

Views/Recruit/Hire.cshtml
@model HRMS.Models.Opening
@{
    ViewBag.Title = "Hire";
}

<div class="box grid_16 tabs">
    <ul class="tab_header clearfix">
        <li><a href="#tabs-1">Job Opening</a></li>
        <li><a href="#tabs-2">Hiring Process</a></li>
        <li><a href="#tabs-3">Add or Assign PIC</a></li>
    </ul>
    <div class="controls">
        <a href="#" class="grabber"></a>
        <a href="#" class="toggle"></a>
        <a href="#" class="show_all_tabs"></a>
    </div>
    <div class="toggle_container">
        <div id="tabs-1" class="block">

            <h2 class="section">Job Opening</h2>
            @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "validate_form" }))
            {
            <fieldset class="label_side label_small top">
                <label for="text_field_inline">Position</label>
                <div>
                     @Html.TextBoxFor(m => m.JobTitle, new { @id = "required_fname", @class = "required" })
                </div>
            </fieldset>

            <fieldset class="label_top">
                <label for="text_field_inline">Job Description</label>
                <div>
                    @Html.TextAreaFor(m => m.JobDesc, new { @id = "tiny_input", @class = " required" })
                </div>
            </fieldset>
            <div class="columns clearfix">
                <div class="col_50">
                    <fieldset class="label_side label_small top">
                        <label for="text_field_inline">Location</label>
                        <div>
                             @Html.TextBoxFor(m => m.Location, new { @id = "required_fname", @class = "required" })
                            <div class="required_tag"></div>
                        </div>
                    </fieldset>
                </div>
                <div class="col_50">
                    <fieldset class="label_side label_small top right">
                        <label for="text_field_inline">Emp Type</label>
                        <div>
                             @Html.TextBoxFor(m => m.EmplType, new { @id = "required_fname", @class = "required" })
                            <div class="required_tag"></div>
                        </div>
                    </fieldset>
                </div>
            </div>
                <div class="button_bar clearfix">
                    <button class="dark" type="submit">
                        <img src="images/icons/small/white/mail.png">
                        <span>Send</span>
                    </button>
                    <button class="light send_right" type="reset">
                        <span>Reset</span>
                    </button>
                </div>
            }

        </div>
        <div id="tabs-2" class="block">
            <div class="columns clearfix">
                <div class="col_100">
                    <fieldset class="bottom">
                        <label>Modify the selection process for this opening. </label>
                        <div>
                            <select class="multisorter indent" multiple="multiple" style="height: 230px;">
                                <option>Red</option>
                                <option>Green</option>
                                <option selected="selected">Blue</option>
                                <option>Cyan</option>
                                <option>Magenta</option>
                                <option selected="selected">Yellow</option>
                                <option>Black</option>
                            </select>
                        </div>
                    </fieldset>
                </div>
            </div>

        </div>

        <div id="tabs-3" class="block">
            <div class="columns clearfix">
                <div class="col_100">
                    <h2 class="box_head  grad_green">Regular Table with Form Inputs</h2>
                    <table class="static">
                        <thead>
                            <tr>
                                <th>Column 1</th>
                                <th>Column 2</th>
                                <th>Column 3</th>
                                <th>Column 4</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <input type="text" /></td>
                                <td>
                                    <input type="text" /></td>
                                <td>
                                    <input type="text" /></td>
                                <td>
                                    <input type="text" /></td>
                                <td>
                                    <button class="div_icon">
                                        <div class="ui-icon ui-icon-plusthick"></div>
                                    </button>
                                </td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>Internet
										 Explorer 4.0</td>
                                <td>Win 95+</td>
                                <td>4</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>Internet
										 Explorer 5.0</td>
                                <td>Win 95+</td>
                                <td>5</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>Internet
										 Explorer 5.5</td>
                                <td>Win 95+</td>
                                <td>5.5</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>Internet
										 Explorer 6</td>
                                <td>Win 98+</td>
                                <td>6</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>Internet Explorer 7</td>
                                <td>Win XP SP2+</td>
                                <td>7</td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Recruit/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Views/Recruit/Stage.cshtml
@model IEnumerable<HRMS.Models.Stage>
@{
    ViewBag.Title = "Stage";
} 

@if(TempData["color"] != null)
{
<div class="box grid_16">
    <div class="toggle_container">
        <div class="block">
            <div class="section"> 
                <div class="alert dismissible alert_@TempData["color"]">
                    <img height="24" width="24" src="~/Content/Images/icons/small/white/facebook_like.png">
                   @TempData["result"]
                </div>  
            </div>
        </div>
    </div>
</div>
}

<div class="grid_12 box clearfix">
    <div class="indented_button_bar clearfix">
        <a href="@Url.Action("StageForm", "Recruit")" class="button blue send_right">
            <span>Create New Stage</span>
        </a> 
    </div>
</div>
<div class="box grid_12">
    <h2 class="box_head">Set Stages for Hiring Process</h2>
    <div class="controls">
        <a href="#" class="grabber"></a>
        <a href="#" class="toggle"></a>
    </div>
    <div class="block">
        <table class="static" id="mytable">
            <tbody>
                @foreach (var stage in Model)
                {
                    <tr style="height: 70px;">
                        <td style="width: 1%; vertical-align: middle" class="customerIDCell">@stage.StageID</td>
                        <td style="width: 70%; vertical-align: middle">@stage.Desc</td>
                        <td style="width: 30%; vertical-align: middle">
                           @Html.HiddenFor(model => stage.StageID)
                            <span class="button light"><a href="#" class="up  uplink">
                                <img src="~/Content/Images/icons/small/grey/bended_arrow_up.png" /></a></span>
                            <span class="button light"><a href="#" class="down uplink">
                                <img src="~/Content/Images/icons/small/grey/bended_arrow_down.png" /></a></span>
                            <span class="button light">
                                @Html.ActionLink("UpdateStage", "UpdateStage", new { id = stage.StageID }, new { @class = "ui-icon ui-icon-pencil" })
                            </span>
                            <span class="button light">
                                @Html.ActionLink("DeleteStage", "DeleteStage", new { id = stage.StageID }, new { @class = "deleteLink ui-icon ui-icon-trash" })
                            </span>
                        </td>
                    </tr> 
                 }
            </tbody>
        </table>

    </div>
</div>

<input type="hidden" id="myField" value="" />

<div class="display_none">
                <div id="confirm-delete" class="dialog_content narrow no_dialog_titlebar" title="Delete Confirmation">
                    <div class="block">
                        <div class="section">
                            <h1>Delete File</h1>
                            <div class="dashed_line"></div>
                            <p>Please confirm that you want to delete this record.</p>
                        </div>
                         
                    </div>
                </div>
            </div>
 
<script>
    $(document).ready(function () {
        
        $(".up,.down").click(function () {
            var row = $(this).parents("tr:first");
            if ($(this).is(".up")) {
                row.insertBefore(row.prev());
            } else {
                row.insertAfter(row.next());
            }
        });

        $("#confirm-delete").dialog({
            autoOpen: false,
            modal: true,
            resizable: false,
            height: 180,
        });

        $(".deleteLink").click(function (e) {
            e.preventDefault();
            var targetUrl = $(this).attr("href");

            $("#confirm-delete").dialog({
                buttons: {
                    "Confirm": function () {
                        window.location.href = targetUrl;
                    },
                    "Cancel": function () {
                        $(this).dialog("close");
                    }
                }
            });

            $("#confirm-delete").dialog("open");
        });

          
        jQuery('.uplink').on('click', function () {
            var items = [], options = [];

            //Iterate all td's in second column
            $('#mytable>tbody>tr>td:nth-child(1)').each(function () {
                //add item to array
                items.push($(this).text());
            });

            //restrict array to unique items
            var items = items; 
            window.location.href = "UpdateStageSeq?seq=" + items;
        });
       

    });


</script>

Views/Recruit/StageForm.cshtml
@model HRMS.Models.Stage
@{
    ViewBag.Title = "CreateStage";
}
  
<div class="box grid_12">
    <h2 class="box_head">Set Stages for Hiring Process</h2>
    <div class="controls">
        <a href="#" class="grabber"></a>
        <a href="#" class="toggle"></a>
    </div>
    <div class="block">


        <table class="static">
            <thead>
                <tr>
                    <th>Column 1</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "validate_form" }))
                {
                    <tr>
                        <td>
                        @Html.TextBoxFor(m => m.Desc, new { @id = "required_desc", @class = "required" })
                        <td>
                            <button class="div_icon">
                                <div class="ui-icon ui-icon-plusthick"></div>
                            </button>
                        </td>
                    </tr>
                                }
            </tbody>
        </table>

    </div>
</div>

Views/Recruit/UpdateStage.cshtml
@model HRMS.Models.Stage
@{
    ViewBag.Title = "Update This Stage";
}
  
<div class="box grid_12">
                    <h2 class="box_head">Set Stages for Hiring Process</h2>
                    <div class="controls">
                        <a href="#" class="grabber"></a>
                        <a href="#" class="toggle"></a>
                    </div>
                    <div class="block">  
                         

                        <table class="static">
                            <thead>
                                <tr>
                                    <th>Column 1</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @using (Html.BeginForm("UpdateStage", "Recruit", FormMethod.Post, new { @class = "validate_form" }))
                                {
                                    <tr>
                                        <td>
                                        @Html.TextBoxFor(m => m.Desc, new { @id = "required_desc", @class = "required" })
                                        <td>
                                            <button class="div_icon">
                                                <div class="ui-icon ui-icon-plusthick"></div>
                                            </button>
                                        </td>
                                    </tr>
            }
                            </tbody>
                        </table>
                        
                    </div>
                </div>